title: EarthInsider Tools
description: Free online tools by EarthInsider
url: "https://tools.earthinsider.in"
baseurl: ""

collections:
  tools:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: tools
    values:
      layout: tool

plugins:
  - jekyll-sitemap

markdown: kramdown
